### ISSUE TITLE
Use @popCount builtin

### ISSUE THREAD

**Issue by Guigui220D** [acristoffers/five_words#1]
Hello! I suggest using the `@popCount` builtin instead of the `bitCount` function as a further optimization :)
Ps: I am one of your students at the UTT and I couldn't help but notice you tried my favorite langage!
Have a nice day

**Comment by acristoffers** [comment]
Hi!

I remember your name and you wouldn’t believe how surprised I was when I saw the email coming in. Thank you very much for the info, I tried to see if there was something like that in the compiler list of builtins but `@popCount` did not pop as something related (pun intended, not ashamed).

Zig is a nice language, I liked it quite a bit.

**Comment by Guigui220D** [comment]
The pleasure is all mine :) hope you will come back to it and give it a shot for bigger projects, it clearly is worth it

**Comment by acristoffers** [comment]
The word "language" is misspelled in you bio.

Do you mind if I ask some questions?

1) If I got it right zig has less pointers being (explicitly) being passed around than C/C++ and instead uses `struct`s to encapsulate them (like arrays, lists, vectors, hashmaps, etc). Is that correct or did I miss something?

2) Is there a difference between `if (a) |b|` and `if (a) |*b|` other than the `const` qualifier of the first? The second is explictly a pointer that has to be dereferenced and the first not, does it mean memory copy happens in the first or is it just a "hidden" pointer?

Those are two things that I got myself wondering at the end, as I looked at the code...

**Comment by Guigui220D** [comment]
Ah thanks, you're right!

Huuuh, maybe you are talking about the default way of passing arguments to functions. Functions arguments are actually const references by default instead of copies likes in c/c++. This is done to avoid unwanted copies, because if you want to pass something AND edit it you either have to explicitely copy it, or pass a non-const pointer. But otherwise I wouldn't say that Zig uses more structures.

There is no difference indeed, as far as I'm aware! They are const references too, so * is a way of saying that you want a pointer without constness protection. So yes, kind of a "hidden pointer". 

For clarification when I said "reference", it's in a conceptual sense as you probably understood, as Zig doesn't have reference syntax unlike C++.

I think this is something that actually makes a lot of sense once you're used to it, and it helps feeling in control of where the memory is. You still have to be careful with aliasing problems just like in c and c++ though, when performing copies and such.

**Comment by acristoffers** [comment]
Thanks ^^
